baseURL = "https://sitodiroberto.netlify.app"
languageCode = "en-us"
title = "SitodiRoberto"
theme = "tema"
paginate = "5"

[menu]
main = []
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "RobertoFretel"
contact_form_action = "#"
copyright = "&copy; SitodiRoberto"
description = "sito di Roberto"
google_analitycs_id = ""
google_tag_manager = ""
home = "Home"
logo = "images/logo.png"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/illustration.svg"
title = "Benvenuti nel SitodiRoberto!"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-github" # themify icon pack https://themify.me/themify-icons
link = "https://github.com/RobeFre20"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
enableInlineShorcodes = true